### ISSUE TITLE
 The text annotations of the two classes are the same.

### ISSUE THREAD

**Issue by qinghuannn** [kennymckormick/pyskl#100]
Hi, I found a typo in Finegym99 annotation file. The text annotations of the two classes are the same (lines 59 and 71 in [https://github.com/kennymckormick/pyskl/blob/main/tools/data/label_map/gym.txt](url). And I tried to email the authors of Finegym, but  I was told "The author's email address has been temporarily disabled".
Could you correct this typo and release the corrcect annotation?

**Comment by kennymckormick** [comment]
Hi, [lingan1996](https://github.com/lingan1996). I just followed the released taxonomy and annotations to create the skeleton dataset for FineGYM, and I'm sorry that I also have no idea about this problem. You can submit an issue under the official repository of FineGYM (https://github.com/SDOlivia/FineGym/issues) for this problem.

**Comment by lingan1996** [comment]
Thanks for your reply. I will try it.
