### ISSUE TITLE
How to change the device (cpu/gpu) when using test.py

### ISSUE THREAD

**Issue by valentin-fngr** [kennymckormick/pyskl#101]
Hi, 

I would like to know how to specify a device when using test.py 
I could not find the corresponding arg

**Comment by kennymckormick** [comment]
Hi, [valentin-fngr](https://github.com/valentin-fngr), we do not directly use `test.py` for testing, but use the bash file `dist_test.sh`. To specify the GPU devices, you can use `CUDA_VISIBLE_DEVICES=0,1,2,3(replace it with the GPU ids you want to use) bash tools/dist_test.sh {config_file} {checkpoint_file} {num_gpus}`. Currently, I'm not sure whether one can test with CPU.
