### ISSUE TITLE
About RGB-Posec3d

### ISSUE THREAD

**Issue by mxy-699699** [kennymckormick/pyskl#105]
Hi, it's really an amazing job! But I didn't find the config about using SlowFast network (there is only SlowOnly network configuration). So could you offer a script about that? Thank you so much

**Comment by kennymckormick** [comment]
Hi, [mxy-699699](https://github.com/mxy-699699), I'm working on adding it to PYSKL recently, will release it once ready.

**Comment by kennymckormick** [comment]
Finally, I have implemented RGBPoseConv3D in PYSKL 🤣 . The implementation is in PR https://github.com/kennymckormick/pyskl/pull/116 and has been merged to the main branch.

**Comment by mxy-699699** [comment]
> Finally, I have implemented RGBPoseConv3D in PYSKL 🤣 . The implementation is in PR #116 and has been merged to the main branch.

That's great. Thank you so much for all your work.
