### ISSUE TITLE
Train model on custom dataset

### ISSUE THREAD

**Issue by xiaoxin-Crayon** [kennymckormick/pyskl#108]
Hello, Thanks for your solid work, I have a little question:
How should I use my own dataset to train model, such as st-gcn..., (for some reasons, I pay more attention to upper limb movements, so my skeleton form does not conform to the standard skeleton format)

**Comment by kennymckormick** [comment]
Hi, xiaoxin. My suggestion is to build a sub-graph for your upper body skeleton annotations. You can define an upper-body graph in https://github.com/kennymckormick/pyskl/blob/main/pyskl/utils/graph.py, and use the defined graph for your skeleton action recognizer.

**Comment by xiaoxin-Crayon** [comment]
Thanks for your reply!
Do I follow these steps to train using the custom dataset:
1. Use the provided diving48_ example generate my Custom Dataset, and select the upper-body keypoints.
2. add my dataset's graph in here: https://github.com/kennymckormick/pyskl/blob/4d32ea9134858c908923a87b14c73abc2e42d6a1/pyskl/utils/graph.py#L89
3. add a config file follow configs/stgcn/stgcn_pyskl_ntu60_xsub_3dkp/j.py
4. then, use this command to train the model: bash tools/dist_train.sh configs/stgcn/stgcn_pyskl_ntu60_xsub_3dkp/mytrainconfig.py
I'm not sure. Could you give me some advice, and the four modalities in config: **Joint, Bone, Joint Motion, and Bone Motion**, what's the difference between them？

**Comment by kennymckormick** [comment]
Basically, Yes. 
Remember you also need to set graph type as `upper_body` (Let's say that's the name of ur new graph). 
The 4 modalities are all derived from joint coordinates (`joint` is the joint coordinates itself). To see the specific generation process, please check class `JointToBone` and `ToMotion` in the `pipelines` folder.

**Comment by wujiangru** [comment]
Hi, I had a similar problem to you. I want to use the NTU60 dataset, but only take the upper limb joints of the human skeleton. How can I modify it?
