### ISSUE TITLE
detection model error in demo

### ISSUE THREAD

**Issue by jeongeun12** [kennymckormick/pyskl#11]
i tried demo_posec3d with st-gcn++ that was trained with ntu60 dataset.
but i got detection error although i download det-checkpoint. detection model is still nontype
![image](https://user-images.githubusercontent.com/93428685/166391361-528b83f9-69c0-4b27-91ab-bb1eb56e65be.png)
i don't know the reason..

**Comment by kennymckormick** [comment]
Please try our latest master branch, the bug is already fixed.
