### ISSUE TITLE
Dataset compose pipeline expalaination? 

### ISSUE THREAD

**Issue by viet-hoang-99** [kennymckormick/pyskl#113]
@kennymckormick,   on the line 137, 138 of pyskl/datasets/pipelines/sampling.py
![Screenshot from 2022-12-21 17-15-21](https://user-images.githubusercontent.com/87934114/208880788-ef1117b9-9468-48d4-a0c2-29b6310fc611.png)
i dont know the meaning of start_index variable, i have read the uniform sampling algorithm and i found that when i run the code without 2 line below, it run completely. But when i used your original code, there was the error: list index out of range and i think it caused of adding start_index to the indicies of clipping list of uniform sampling (it always + 1 to the indicies and make list out of range). Could you please check your code or explain whether i missed something?

**Comment by kennymckormick** [comment]
Hi, [viet-hoang-99](https://github.com/viet-hoang-99), 
I think that in this codebase, 'start_index' is always set 0. You can find that the default value of start_index is set to 0 in both PoseDataset and VideoDataset. You are experiencing some unexpected behavior, and I think the possible reason is that you implement a new dataset based on the BaseDataset, but forget to set start_index to 0.
