### ISSUE TITLE
About Training Epochs

### ISSUE THREAD

**Issue by Altair-yang** [kennymckormick/pyskl#118]
The Training Epochs is 240 in "Readme.md", but 24  in "joint.py". Could you tell me what setting is for the best resulting?Thanks!
![image](https://user-images.githubusercontent.com/90332613/210121093-0bcaecfd-1f5d-4b2d-b704-b81d2e751581.png)
![image](https://user-images.githubusercontent.com/90332613/210121191-6a01fa5f-dc3e-47a3-a620-2605af471db9.png)

**Comment by kennymckormick** [comment]
The config is still using 240 epochs: 
![image](https://user-images.githubusercontent.com/34324155/210161330-9e437fe9-a5f6-4490-bbf1-1732e02ddb46.png)

Since I'm using a `RepeatDataset` with `times` set to 10 (for saving time between epoch switches), it's still 24 x 10 = 240 epochs.

**Comment by Altair-yang** [comment]
> The config is still using 240 epochs: ![image](https://user-images.githubusercontent.com/34324155/210161330-9e437fe9-a5f6-4490-bbf1-1732e02ddb46.png)
> 
> Since I'm using a `RepeatDataset` with `times` set to 10 (for saving time between epoch switches), it's still 24 x 10 = 240 epochs.

Thank you!
