### ISSUE TITLE
demo_posec3d

### ISSUE THREAD

**Issue by thmteam2000** [kennymckormick/pyskl#12]
Hi!
We tried to execute demo_posec3d, but there is a problem with init_detector.
The result of init_detector model is None type.
So model.CLASS[0] also has no value.
How can I solve this problem??
<img width="423" alt="image" src="https://user-images.githubusercontent.com/93187899/166391529-13ee8b1f-21bc-4ee7-8e2c-6c378682aa37.png">

**Comment by kennymckormick** [comment]
Hey, thmteam2000, 
Please try our latest master branch, we provide detailed instructions for demo and have fixed this bug.
