### ISSUE TITLE
About RGBPoseConv3D to train UCF101 and HMDB51 datasets

### ISSUE THREAD

**Issue by tty818** [kennymckormick/pyskl#122]
How to use RGBPoseConv3D to train UCF101 and HMDB51 datasets？
Looking forward to your reply

**Comment by kennymckormick** [comment]
Hi, tty818,
Currently, that's not supported in PYSKL. To support this, you need to support a data pipeline component that supports jointly sampling RGB frames and human skeleton from UCF-style skeleton annotations. You can follow the NTURGB+D example to implement that.
