### ISSUE TITLE
HOW TO RUN DGSTGCN

### ISSUE THREAD

**Issue by jeffreyking23** [kennymckormick/pyskl#125]
i run with this :

python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4 --config configs/dgstgcn/ntu120_xset_3dkp/b.py --checkpoint http://download.openmmlab.com/mmaction/pyskl/ckpt/dgstgcn/ntu120_xset_3dkp/b.pth

but i got error:

File "demo/demo_skeleton.py", line 243, in main
    GCN_nperson = format_op['num_person']
  File "D:\Anaconda3\envs\action_recognition\lib\site-packages\mmcv\utils\config.py", line 37, in __missing__
    raise KeyError(name)
KeyError: 'num_person'

Can you provide the right demo script to run DGSTGCN?

**Comment by kennymckormick** [comment]
Hi, jeffreyking23, 
That's problem is due to the missing of default value of `num_person`, I have fixed it in #128
