### ISSUE TITLE
custom kinetics-skeleton dataset

### ISSUE THREAD

**Issue by MikuuGithub** [kennymckormick/pyskl#126]
我使用custom_2d_skeleton.py脚本，对kinetics400中的50个视频进行关键点提取，但是我遇到一个令人头疼的问题：
当前视频中只有一个人，但是fasterrcnn检测器却总是能检测到两个人，并且置信度很高，以至于无法通过det_area_thr筛选：下面是debug查看det_results中内容。请求您的帮助！please！
![img_000065](https://user-images.githubusercontent.com/24295745/213369987-af7aea27-a594-4b0f-a50e-c5f8d6f94e93.jpg)
![image](https://user-images.githubusercontent.com/24295745/213369490-dc245085-2263-4e52-9864-de2e7da861c3.png)

**Comment by kennymckormick** [comment]
Seems you have two highly overlapping proposals. One solution to add some heuristic nms ops for pre-processing. For example, for two boxes with iou larger than a threshold, you can keep the larger box and drop the smaller one.

**Comment by MikuuGithub** [comment]
Thanks，i will try.
