### ISSUE TITLE
stuck in extract_diving48_skeleton

### ISSUE THREAD

**Issue by sasakits** [kennymckormick/pyskl#132]
Hi, Thank you for your great work.

At diving48_example.ipynb Step 3: Extract 2D skeleton for Diving48 Videos
I am facing error message with this command. I have tried to solve it but I could not it for now.

Please let me know if someone can help me.

**Command** 
`bash tools/dist_run.sh tools/data/custom_2d_skeleton.py 1 --video-list examples/extract_diving48_skeleton/diving48.list --out examples/extract_diving48_skeleton/diving48_annos.pkl`

**Error Message**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sasaki/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/sasaki/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'tools/data/custom_2d_skeleton.py', '--local_rank=0', '--video-list', 'examples/extract_diving48_skeleton/diving48.list', '--out', 'examples/extract_diving48_skeleton/diving48_annos.pkl']
' died with <Signals.SIGSEGV: 11>.
```

**Comment by kennymckormick** [comment]
That's great! Can you figure out what caused the problem? Cuz I never met it on my servers.
