### ISSUE TITLE
Why does the pyskl use so much GPU memory?

### ISSUE THREAD

**Issue by tingweiwang** [kennymckormick/pyskl#14]
Does the data pipeline,  for example the train_pipeline in "configs/stgcn++/stgcn++_ntu60_xview_3dkp/j.py", use GPU? The pyskl occupies more GPUs memory than mmaction2, at least 2 times.

**Comment by kennymckormick** [comment]
Hi, tingweiwang, 
Are you sure about this? 
I run training with this config, the memory number in log is 3458MB (16 samples / per GPU).
Meanwhile, for MMAction2, if you run ST-GCN + NTURGB+D 3D skeleton, the memory consumption is 10019MB (32 samples / per GPU).
