### ISSUE TITLE
Pretrain the posec3d encoder

### ISSUE THREAD

**Issue by azelee** [kennymckormick/pyskl#144]
I'd like to pre-train the posec3d model by some self-supervised method , but I feel diffcult when extract the poseC3D encoder in the repository among the directory, I want some help about the inner running logit about the code, thanks

**Comment by kennymckormick** [comment]
PoseC3D is just a 3D-CNN with heatmap volumes as inputs. To train it with SSL methods (suppose you are talking about MoCo, SimSiam, etc.), you can process the final output feature with global average pooling to obtain a feature vector for each video clip, then use them in standard SSL pipelines.
