### ISSUE TITLE
The video generated after running the demo is black

### ISSUE THREAD

**Issue by SCsleepy** [kennymckormick/pyskl#145]
When the demo is running, everything is normal, but the generated demo/demo.mp4 is black for 3 seconds after it is opened, as is the case in both demos.
<img width="405" alt="Demo Playback" src="https://user-images.githubusercontent.com/117082999/224677039-6da06701-6fe9-4f9d-bc2e-15732dbbc61e.png">
<img width="976" alt="Demo run results" src="https://user-images.githubusercontent.com/117082999/224677057-25b83a87-fee4-4472-891b-edee4914c30b.png">

**Comment by kennymckormick** [comment]
Perhaps it's due to the compatibility of your player. You can try to use VLC to play the video.

**Comment by SCsleepy** [comment]
> 



> Perhaps it's due to the compatibility of your player. You can try to use VLC to play the video.

Thank you very much for using your method to succeed
