### ISSUE TITLE
mmpose.apis problem : inference_top_down_pose_model

### ISSUE THREAD

**Issue by leo06111** [kennymckormick/pyskl#146]
hi , i try to use pyskl to inference as the demo.md. but i encounter this problem

File "/content/pyskl/demo/demo_skeleton.py", line 309, in <module>
    main()
  File "/content/pyskl/demo/demo_skeleton.py", line 253, in main
    pose_results = pose_inference(args, frame_paths, det_results)
  File "/content/pyskl/demo/demo_skeleton.py", line 180, in pose_inference
    pose = inference_top_down_pose_model(model, f, d, format='xyxy')[0]
TypeError: 'NoneType' object is not subscriptable

it seems that the function 'inference_top_down_pose_model' is coming from the mmpose.apis. 
my mmcv-full==1.5.0 , mmdet==2.28.2 , mmpose==0.29.0

thanks you!

**Comment by kennymckormick** [comment]
You need to check if `model` is None. If so, that means you failed to build an mmpose model, and the recommended further step is to fix your mmpose installation.

**Comment by leo06111** [comment]
dear kennymckormick ~
i open the demo_skeleton.py , and print the model , it return None , 
so i turn to use mmpose==0.25.0 , mmdet==2.23.0 , mmcv-full==1.5.0
but it still return the same error.

could you tell me which specifically to fix in the mmpose module?
thank you!

**Comment by kennymckormick** [comment]
Please try to follow the [new installation guide](https://github.com/kennymckormick/pyskl/blob/051a094f9de6cbe9ddeb1f3a8f2754629691ca42/README.md?plain=1#L46) to reinstall pyskl and see if the problem has been fixed now.
