### ISSUE TITLE
My own skeleton data

### ISSUE THREAD

**Issue by chanwo0kim** [kennymckormick/pyskl#148]
Hello! I have some questions about your work!

First of all, congratulations on your research success.

I'm trying to learn poseC3D with my own dataset. 

Since this dataset does not have 17 joints like COCO (25, 67, etc.), I want to use all of these joints for training.

So, I tried to train by increasing in_channels of **joint.py**, but the performance was not very good compared to 17-joints case.

However, I think that the more skeletons are used, the denser the expression. 

This should have led to better performance, but it didn't.

The reason I think is as follows:

1. When using 81 joints as input, the base channel must be greatly increased.

2. The order of 81 joints has meaning.

3. If 81 are projected in 2D, there are many similar joints in the image, which hinders training.

I think number 2 is the most likely. 

Is there meaning in skeleton ordering?

Or is there another reason?

We will wait for your reply.

Thank you!

**Comment by kennymckormick** [comment]
Hi, chanwo0kim, 
As far as I know, all listed reasons will not affect the model performance. A reasonable guess is that you should find another suitable set of hyper-parameters for your own dataset.
