### ISSUE TITLE
error in "python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4"

### ISSUE THREAD

**Issue by VisImage** [kennymckormick/pyskl#15]
Thanks for sharing the implementation. When running the demo, the following error message. Please advice.

(pyskl) D:\gitSources\pyskl>python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
load checkpoint from http path: https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth
Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 309, in <module>
    main()
  File "demo/demo_skeleton.py", line 250, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_skeleton.py", line 157, in detection_inference
    assert model.CLASSES[0] == 'person', ('We require you to use a detector '
AttributeError: 'NoneType' object has no attribute 'CLASSES'

(pyskl) D:\gitSources\pyskl>

Computer:
Y720
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
16.0 GB (15.9 GB usable)
NVIDIA GeForce GTX 1060
Windows 10 Home

Installation:
conda create -n pyskl python=3.8 pytorch=1.10 cudatoolkit=11.3 torchvision -c pytorch -y  
pip install -r requirements.txt   
pip install -e .

**Comment by lucheng07082221** [comment]
I meet the same error!

**Comment by kennymckormick** [comment]
Hi, VisImage,
I can run this demo on my linux server, would you please provide more details, like your mmdet, mmpose version?

![image](https://user-images.githubusercontent.com/34324155/167290976-6fadf3c8-c163-4d86-80fb-f82aef4f058b.png)

**Comment by lucheng07082221** [comment]
![Uploading Screenshot from 2022-05-08 17-59-32.png…]()

**Comment by lucheng07082221** [comment]
lc@lc:~/pyskl-0.1$ python3 demo/demo_posec3d.py demo/ntu_sample.avi demo/demo.mp4 --config /home/lc/pyskl-0.1/configs/posec3d/slowonly_r50_ntu120_xsub/joint.py
Use load_from_http loader
Traceback (most recent call last):
  File "demo/demo_posec3d.py", line 255, in <module>
    main()
  @kennymckormick 

File "demo/demo_posec3d.py", line 204, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_posec3d.py", line 158, in detection_inference
    assert model.CLASSES[0] == 'person', ('We require you to use a detector '
AttributeError: 'NoneType' object has no attribute 'CLASSES'

**Comment by lucheng07082221** [comment]
@kennymckormick 


lc@lc:~/work/pyskl$ python3 demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
load checkpoint from http path: https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth
Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 309, in <module>
    main()
  File "demo/demo_skeleton.py", line 250, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_skeleton.py", line 157, in detection_inference
    assert model.CLASSES[0] == 'person', ('We require you to use a detector '
AttributeError: 'NoneType' object has no attribute 'CLASSES'
lc@lc:~/work/pyskl$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyskl,mmcv,mmdet,mmpose
>>> print(pyskl.__version__, mmcv.__version__, mmdet.__version__,mmpose.__version__)
0.1.0 1.3.17 2.23.0 0.24.0
>>>

**Comment by lucheng07082221** [comment]
lc@lc:~/work/pyskl$ python3 demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4

load checkpoint from http path: https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth

Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 309, in <module>
    main()
  File "demo/demo_skeleton.py", line 250, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_skeleton.py", line 157, in detection_inference
    assert model.CLASSES[0] == 'person', ('We require you to use a detector '
AttributeError: 'NoneType' object has no attribute 'CLASSES'
lc@lc:~/work/pyskl$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyskl,mmcv,mmdet,mmpose
>>> print(pyskl.__version__, mmcv.__version__, mmdet.__version__,mmpose.__version__)
0.1.0 1.3.17 2.23.0 0.24.0

**Comment by kennymckormick** [comment]
> lc@lc:~/work/pyskl$ python3 demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
> 
> load checkpoint from http path: https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth
> 
> Traceback (most recent call last): File "demo/demo_skeleton.py", line 309, in main() File "demo/demo_skeleton.py", line 250, in main det_results = detection_inference(args, frame_paths) File "demo/demo_skeleton.py", line 157, in detection_inference assert model.CLASSES[0] == 'person', ('We require you to use a detector ' AttributeError: 'NoneType' object has no attribute 'CLASSES' lc@lc:~/work/pyskl$ python3 Python 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import pyskl,mmcv,mmdet,mmpose
> > > > print(pyskl.**version**, mmcv.**version**, mmdet.**version**,mmpose.**version**)
> > > > 0.1.0 1.3.17 2.23.0 0.24.0

Hi, lucheng, I can run the demo on my linux server with exactly the same codebase version as your: 
![image](https://user-images.githubusercontent.com/34324155/167292602-e571d515-a3a2-4741-ba5f-13eb8d3fd118.png)

Maybe you can try to:
1. Check if you have installed mmcv-full, this demo requires mmcv-full

**Comment by lucheng07082221** [comment]
yes you are right ,my mmcv version is too old



---Original---
From: "Haodong ***@***.***&gt;
Date: Sun, May 8, 2022 18:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kennymckormick/pyskl] error in "python demo/demo_skeleton.pydemo/ntu_sample.avi demo/demo.mp4" (Issue #15)




  
***@***.***:~/work/pyskl$ python3 demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
 
load checkpoint from http path: https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth
 
Traceback (most recent call last): File "demo/demo_skeleton.py", line 309, in main() File "demo/demo_skeleton.py", line 250, in main det_results = detection_inference(args, frame_paths) File "demo/demo_skeleton.py", line 157, in detection_inference assert model.CLASSES[0] == 'person', ('We require you to use a detector ' AttributeError: 'NoneType' object has no attribute 'CLASSES' ***@***.***:~/work/pyskl$ python3 Python 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
    
import pyskl,mmcv,mmdet,mmpose
 print(pyskl.version, mmcv.version, mmdet.version,mmpose.version)
 0.1.0 1.3.17 2.23.0 0.24.0
     
Hi, lucheng, I can run the demo on my linux server with exactly the same codebase version as your:
 
 
Maybe you can try to:
  
Check if you have installed mmcv-full, this demo requires mmcv-full

**Comment by VisImage** [comment]
Does this repo run on Windows?  I'll try it on Ubuntu 20.04. Would you please share you computer specifications? Thanks.

**Comment by kennymckormick** [comment]
> Does this repo run on Windows? I'll try it on Ubuntu 20.04. Would you please share you computer specifications? Thanks.

Hi, VisImage,
You can run training and testing on Windows without any difficulty. 
For demo_skeleton.py, since it depends on mmcv-full, if you have installed mmcv-full on your windows machine, then you can run the demo_skeleton successfully.

**Comment by VisImage** [comment]
Tested, progressing but still have errors, (as shown below).  Not easy to use the trial and error here. Will try more when get choice.

========================================================
Install the repo on Ubuntu 18.04 (a fresh installed OS)
========================================================
(base) peter@Y720:~/gitSources$ conda create -n open-mmlab python=3.8 pytorch=1.10 cudatoolkit=11.3 torchvision -c pytorch -y

(base) peter@Y720:~/gitSources$ conda activate open-mmlab
(open-mmlab) peter@Y720:~/gitSources$ pip3 install openmim
(open-mmlab) peter@Y720:~/gitSources$ mim install mmcv-full
(open-mmlab) peter@Y720:~/gitSources$ git clone https://github.com/kennymckormick/pyskl.git
(open-mmlab) peter@Y720:~/gitSources$ cd pyskl
(open-mmlab) peter@Y720:~/gitSources/pyskl$ pip install -r requirements.txt
(open-mmlab) peter@Y720:~/gitSources/pyskl$ pip install -e .
(open-mmlab) peter@Y720:~/gitSources/pyskl$ python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
load checkpoint from http path: https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth
Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 309, in <module>
    main()
  File "demo/demo_skeleton.py", line 250, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_skeleton.py", line 157, in detection_inference
    assert model is not None, 'Failed to build the detection model. Check if you have installed mmcv-full properly.'
AssertionError: Failed to build the detection model. Check if you have installed mmcv-full properly.
========================================================
Uninstall mmcv-full==1.5.0 and install mmcv-full ==1.3.18
=========================================================
peter@Y720:~/gitSources/pyskl$ python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 30, in <module>
    from mmpose.apis import init_pose_model, inference_top_down_pose_model, vis_pose_result
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottom_up_pose_model,
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/apis/inference.py", line 15, in <module>
    from mmpose.datasets.dataset_info import DatasetInfo
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/datasets/__init__.py", line 7, in <module>
    from .datasets import (  # isort:skip
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/datasets/datasets/__init__.py", line 2, in <module>
    from ...deprecated import (TopDownFreiHandDataset, TopDownOneHand10KDataset,
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/deprecated.py", line 5, in <module>
    from .datasets.datasets.base import Kpt2dSviewRgbImgTopDownDataset
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/datasets/datasets/base/__init__.py", line 2, in <module>
    from .kpt_2d_sview_rgb_img_bottom_up_dataset import \
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_bottom_up_dataset.py", line 8, in <module>
    from xtcocotools.coco import COCO
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/xtcocotools/coco.py", line 58, in <module>
    from . import mask as maskUtils
  File "/home/peter/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/xtcocotools/mask.py", line 3, in <module>
    import xtcocotools._mask as _mask
  File "xtcocotools/_mask.pyx", line 1, in init xtcocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by kennymckormick** [comment]
> 18.04 (a fresh installed OS)

Maybe you also need to reinstall mmdet and mmpose after installing mmcv-full.

**Comment by bingnoi** [comment]
hi i have already installed mmcv-full 1.3.14, but it report that 
![image](https://user-images.githubusercontent.com/53188228/168084355-c7370018-cc39-4ddf-8a22-c8e5faa5a474.png)
