### ISSUE TITLE
Different training and testing results were obtained using the same random seeds on the same machine

### ISSUE THREAD

**Issue by AgileChen3** [kennymckormick/pyskl#156]
Different training and testing results were obtained using the same random seeds on the same machine

**Comment by kennymckormick** [comment]
Currently we do not have a mechanism to ensure that the model in different runs will have exactly the same accuracy. But the difference may not be large (at most ~0.3% difference according to my experience). If you witness a larger difference, please paste the logs of different runs and the config you used for training for further investigation.
