### ISSUE TITLE
error when run python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4

### ISSUE THREAD

**Issue by HichemSaoudi** [kennymckormick/pyskl#159]
When running the demo, the following error message. Please advice.

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
load checkpoint from local path: .cache/joint_f6bed715.pth
load checkpoint from http path: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person/faster_rcnn_r50_fpn_1x_coco-person_20201216_175929-d022e227.pth
Performing Human Detection for each frame
[>>] 72/72, 6.7 task/s, elapsed: 11s, ETA:     0sPerforming Human Pose Estimation for each frame
[                                                  ] 0/72, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/content/pyskl/demo/demo_skeleton.py", line 309, in <module>
    main()
  File "/content/pyskl/demo/demo_skeleton.py", line 253, in main
    pose_results = pose_inference(args, frame_paths, det_results)
  File "/content/pyskl/demo/demo_skeleton.py", line 177, in pose_inference
    pose = inference_top_down_pose_model(model, f, d, format='xyxy')[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by kennymckormick** [comment]
Did you setup the environment of pyskl following the provided guideline: https://github.com/kennymckormick/pyskl/blob/faf6f2adee20651fe2730840a70a509eb77a732a/README.md?plain=1#L46? 
If not you can follow that and try again.
