### ISSUE TITLE
There may be some bugs here.

### ISSUE THREAD

**Issue by MikuuGithub** [kennymckormick/pyskl#16]
When i run the demo_skeleton.py with http://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_346_k400/joint.pth(slowonly_r50_346_k400/joint.py), there some information like this:
![346_joint pth](https://user-images.githubusercontent.com/24295745/167323160-0e8e0d3c-6961-4089-9cc0-7ce9ef0c8624.png)

**Comment by kennymckormick** [comment]
Currently, demo_skeleton is not compatible with posec3d_k400, we are working on this.

**Comment by kennymckormick** [comment]
Hi, MikuuGithub, 
The bug is already fixed in https://github.com/kennymckormick/pyskl/pull/24, now you can try the latest code. It can use k400 pretrained posec3d for demo_skeleton.

**Comment by MikuuGithub** [comment]
> Hi, MikuuGithub, The bug is already fixed in #24, now you can try the latest code. It can use k400 pretrained posec3d for demo_skeleton.

Thanks for your a lot!
