### ISSUE TITLE
general custom dataset setting

### ISSUE THREAD

**Issue by yuchen-ji** [kennymckormick/pyskl#167]
Thanks for your solid work.
If I want to collect a custom dataset, approximately including less than 10 types of simple actions. How much video data needs to be collected for each action?

**Comment by kennymckormick** [comment]
Hi, @yuchen-ji , 
The specific number of videos used for training may depends on your data quality and action categories. Generally speaking, I think you can try to train your skeleton action recognition model after collecting more than 10 samples per action category.

**Comment by yuchen-ji** [comment]
Thank you so much.
Generally speaking, do you think it is suitable to set 100 sets of videos for each action, when action recognition is done from similar perspectives?

**Comment by kennymckormick** [comment]
> 
100 videos / action is sufficient for training I guess.

**Comment by yuchen-ji** [comment]
Thank you for your suggestion.
I will first train with 100 videos per action.
