### ISSUE TITLE
RGBPoseConv3D ——“Invalid data found when processing input”

### ISSUE THREAD

**Issue by whisper0411** [kennymckormick/pyskl#175]
When I try to **test the RGBPoseConv3D model according to instructions**, I always encounter the following error：
<img width="937" alt="image" src="https://user-images.githubusercontent.com/40971393/236210246-18738430-1865-42eb-9efb-75afb0e3c5f8.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/40971393/236209795-c554349d-2106-411c-823c-493811e21b22.png">
Here are more detailed error reports：
<img width="854" alt="image" src="https://user-images.githubusercontent.com/40971393/236211401-bc43b652-5c61-40a9-8893-fbf55bcdd881.png">
I can not figure out what wrong with the model or the data. Could you kindly check why this is happening?
Thanks a lot!!!!!!!!!!

**Comment by tribeband** [comment]
how to fix this
