### ISSUE TITLE
(demo_gesture.py) Segfault when running the script

### ISSUE THREAD

**Issue by MengZhongKuan** [kennymckormick/pyskl#210]
**Environment**
WSL: Linux DESKTOP-ICND2FE 5.15.90.1-microsoft-standard-WSL2+ #1 SMP Fri Nov 3 15:18:26 CDT 2023 x86_64 x86_64 x86_64 GNU/Linux  

**Issue**
- Segmentation fault encountered when the script is run with any pyskl functions included.
- cv2.imshow works fine when none of the pyskl functions are included.
- cv2.imshow encounters segmentation fault when any functions from pyskl is included. (Even if none of the functions imported are called)

**Lead-up**
- Followed installation instructions in README.md and demo.md.

**Comment by MengZhongKuan** [comment]
Here is the error log. Note: This issue only happens when both pyskl and cv2.imshow is used simultaneously.

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
load checkpoint from local path: demo/hagrid.pth
(480, 640, 3) uint8
Segmentation fault

**Comment by sight96** [comment]
hello，how did you solve it？
