### ISSUE TITLE
Can't run python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4

### ISSUE THREAD

**Issue by zhangfusheng-163** [kennymckormick/pyskl#22]
load checkpoint from http path: https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth
load checkpoint from http path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 72/72, 20.9 task/s, elapsed: 3s, ETA:     0sload checkpoint from http path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
Performing Human Pose Estimation for each frame
[                                                  ] 0/72, elapsed: 0s, ETA:Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 314, in <module>
    main()
  File "demo/demo_skeleton.py", line 258, in main
    pose_results = pose_inference(args, frame_paths, det_results)
  File "demo/demo_skeleton.py", line 184, in pose_inference
    pose = inference_top_down_pose_model(model, f, d, format='xyxy')[0]
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/apis/inference.py", line 380, in inference_top_down_pose_model
    poses, heatmap = _inference_single_pose_model(
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/apis/inference.py", line 247, in _inference_single_pose_model
    data = test_pipeline(data)
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/datasets/pipelines/shared_transform.py", line 107, in __call__
    data = t(data)
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmpose/datasets/pipelines/top_down_transform.py", line 289, in __call__
    c = results['center']
KeyError: 'center'

I can't run pose_infererce ,but the frame_paths and det_results are not none,I don't know where is wrong.

**Comment by zhangfusheng-163** [comment]
I have solve this question ,because the mmpose and mmdet are too higher

**Comment by krronk** [comment]
Can you list the compatible versions of torch, 
 mmcv-full, mmdet, mmpose

**Comment by kennymckormick** [comment]
Please provide the version of packages you used.

**Comment by krronk** [comment]
i ran it on colab for stgcn++ and posec3d  with torch=1.11.0, mmcv-full=1.5.0, mmdet=2.23.0, mmpose=0.25.0

**Comment by mei-727** [comment]
Is there a solution？

**Comment by mei-727** [comment]
Checked，it's useful。（mmcv-full=1.5.0, mmdet=2.23.0, mmpose=0.25.0）

**Comment by bridgeqiqi** [comment]
> Can you list the compatible versions of torch,
> mmcv-full, mmdet, mmpose

I have met the same issue, but it works after installing the suitable version of mmdet (2.23.0) and mmpose (0.25.0). Thanks.

**Comment by zhangfusheng-163** [comment]
mmcv-full=1.3.18, mmdet=2.23.0, mmpose=0.24.0

**Comment by kennymckormick** [comment]
> mmcv-full=1.3.18, mmdet=2.23.0, mmpose=0.24.0

These versions are OK. If you still failed to run the demo, try to create a new environment, first install mmcv-full and then install mmdet, mmpose, pyskl.

**Comment by ycj1124** [comment]
![image](https://user-images.githubusercontent.com/55937464/171163773-7f045202-3811-492a-8be2-8f52620b183b.png)
I  met the same error .and this is my version.could the problem be that my version is a little high?

**Comment by kennymckormick** [comment]
> ![image](https://user-images.githubusercontent.com/55937464/171163773-7f045202-3811-492a-8be2-8f52620b183b.png) I met the same error .and this is my version.could the problem be that my version is a little high?

We have updated the pose estimation config file, now it is compatible with mmpose v0.26.0
