### ISSUE TITLE
fail to run demo

### ISSUE THREAD

**Issue by bingnoi** [kennymckormick/pyskl#23]
hi i have already installed mmcv-full 1.3.14, but it report that
![image](https://user-images.githubusercontent.com/53188228/168318997-8efc3bb2-82bd-4c31-a87a-3c24545c1aa3.png)
furthermore, when i check mmcv-full following the mmcv instructions, there is no failure report at all.
![image](https://user-images.githubusercontent.com/53188228/168319077-f58b3ede-3bfc-4d6f-b9ca-2c3b2e8567de.png)

**Comment by kennymckormick** [comment]
Hi, bingnoi, 
You should first install mmcv-full successfully, and then install mmdet, check if your order is correct. 
If it still doesn't work, you can raise an issue under mmdetection, to ask why you failed to build the detection model.
