### ISSUE TITLE
how to fuse different type of models?

### ISSUE THREAD

**Issue by LostDawn** [kennymckormick/pyskl#25]
Is there any script for two-stream model fusion? Or I should use the result.pkl and fuse them by myself?

**Comment by kennymckormick** [comment]
Yes, you should use the result.pkl and fuse it by urself.

**Comment by LostDawn** [comment]
Fine, thanks.

**Comment by lpp123456** [comment]
> Yes, you should use the result.pkl and fuse it by urself.

How did you fuse the result.pkl? Average or weighted summation？Can you tell us the fusion details on different datasets? Thanks!
