### ISSUE TITLE
How to obtain the test score of PoseConv3D on NTU60-Xsub(SlowOnly-R50/joint)

### ISSUE THREAD

**Issue by sieannHit** [kennymckormick/pyskl#28]
I would like to reproduce the 93.7% Mean Top-1 score of PoseConv3D, on NTU60-Xsub(SlowOnly-R50/joint), by using 8 GPUs and inheriting the same setups, but the best outcome are  top1_acc 0.9338 and mean_class_accuracy 0.9337 in the 24 epoch, there is a 0.32% gap. Moreover, the best scores of your log file (https://download.openmmlab.com/mmaction/skeleton/posec3d/slowonly_r50_u48_240e_ntu60_xsub_keypoint/slowonly_r50_u48_240e_ntu60_xsub_keypoint.log) are top1_acc 0.9352 and mean_class_accuracy 0.9351 in the 23 epoch,  it is also a 0.18% gap compared to 93.7%.  

The reason may be that my test method is wrong, are there any settings that need to be adjusted?

**Comment by kennymckormick** [comment]
Hi, sieannHit, 
When you are saying Top-1 score, you mean validation Top-1 or testing Top-1? Actually, they are different. In testing, we use a much heavier data augmentation (10 clip * 2 [flip and no flip]). Thus the performance is better than validation. The log file only shows validation Top-1.
BTW, you can first test with our released ckpt, to see if you can reach 93.7%. If it works, then training with PYSKL and check the **testing** Top-1.
