### ISSUE TITLE
run python demo/demo_skeleton.py demo/ntu_sample.avi command successfully, but generated video can't be played.

### ISSUE THREAD

**Issue by dongxiaolong** [kennymckormick/pyskl#31]
`(pyskl) dong@dong-HP-Z1-Entry-Tower-G6:~/Code/Pyskl/pyskl$ python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
load checkpoint from local path: .cache/joint_f6bed715.pth
load checkpoint from http path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 72/72, 11.9 task/s, elapsed: 6s, ETA:     0sload checkpoint from http path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
Performing Human Pose Estimation for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 72/72, 13.9 task/s, elapsed: 5s, ETA:     0sload checkpoint from http path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
Moviepy - Building video demo/demo.mp4.
Moviepy - Writing video demo/demo.mp4

Moviepy - Done !                                                                                                                                                                                           
Moviepy - video ready demo/demo.mp4
`
Its' seems fine, but the generated video can't be played normally. It's just a black screen, stucked at 00:00.

**Comment by dongxiaolong** [comment]
![image](https://user-images.githubusercontent.com/23193031/169487437-c58740e2-ee86-4ef5-8abc-83bc1fa6fa9c.png)

**Comment by kennymckormick** [comment]
Seems to be a compatibility problem. Please try to play with the VLC player.

**Comment by dongxiaolong** [comment]
> Seems to be a compatibility problem. Please try to play with the VLC player.

Thanks for you help, issue was settled.
