### ISSUE TITLE
how to train diving48 with single GPU?

### ISSUE THREAD

**Issue by insist-arui** [kennymckormick/pyskl#32]
bash tools/dist_train.sh pyskl/configs/posec3d/slowonly_r50_diving48/joint.py   Sorry,i am a 
newer,is this the command to train with single GPU?

**Comment by insist-arui** [comment]
i dont konw how to train with singe GPU,what is the command,thanks for you

**Comment by kennymckormick** [comment]
bash tools/dist_train.sh pyskl/configs/posec3d/slowonly_r50_diving48/joint.py 1
