### ISSUE TITLE
 error: unrecognized arguments: --ckpt

### ISSUE THREAD

**Issue by dongxiaolong** [kennymckormick/pyskl#36]
when I run command: `  python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4 --config configs/stgcn++/stgcn++_ntu120_xsub_hrnet/j.py --ckpt http://download.openmmlab.com/mmaction/pyskl/ckpt/stgcnpp/stgcnpp_ntu120_xsub_hrnet/j.pth`
I get an error:
usage: demo_skeleton.py [-h] [--config CONFIG] [--checkpoint CHECKPOINT] [--det-config DET_CONFIG] [--det-checkpoint DET_CHECKPOINT]
                        [--pose-config POSE_CONFIG] [--pose-checkpoint POSE_CHECKPOINT] [--det-score-thr DET_SCORE_THR] [--label-map LABEL_MAP]
                        [--device DEVICE] [--short-side SHORT_SIDE]
                        video out_filename
demo_skeleton.py: error: unrecognized arguments: --ckpt http://download.openmmlab.com/mmaction/pyskl/ckpt/stgcnpp/stgcnpp_ntu120_xsub_hrnet/j.pth

**Comment by kennymckormick** [comment]
Sorry, that's a typo, --ckpt should be --checkpoint, I have fixed this problem.
