### ISSUE TITLE
Can't run python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4

### ISSUE THREAD

**Issue by HaleYan** [kennymckormick/pyskl#37]
/pyskl-main$ python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4

Traceback (most recent call last):
  
File "demo/demo_skeleton.py", line 16, in <module>
    
from pyskl.apis import inference_recognizer, init_recognizer

ModuleNotFoundError: No module named 'pyskl'

when I run the demo_skeleton.py, it wrong

**Comment by zhangfusheng-163** [comment]
The base env is wrong

**Comment by HaleYan** [comment]
Fine, thanks.
