### ISSUE TITLE
what is the command to train with single GPU on diving48?

### ISSUE THREAD

**Issue by insist-arui** [kennymckormick/pyskl#41]
sir,what is the command to train with single GPU?My command is bash tools/dist_test.sh configs/posec3d/slowonly_r50_diving48/joint.py  work_dirs/posec3d/slowonly_r50_diving48/joint/latest.pth  1 --out yaml/testwork.json --eval top_k_accuracy mean_class_accuracy  , the error is  KeyError 'val'.

**Comment by wyz0916-gitHub** [comment]
Hi,how to run the training part of the code?

**Comment by insist-arui** [comment]
> Hi,how to run the training part of the code?

bash tools/dist_train.sh  configs/posec3d/slowonly_r50_diving48/joint.py   1

**Comment by wyz0916-gitHub** [comment]
Thank you for your help!

**Comment by wyz0916-gitHub** [comment]
Hello, I have finished the training. Have you finished the test part?

**Comment by insist-arui** [comment]
finished.Which benchmark you train?


| |
邸继锐
|
|
***@***.***
|
签名由网易邮箱大师定制
On 5/29/2022 ***@***.***> wrote：

Hello, I have finished the training. Have you finished the test part?

**Comment by wyz0916-gitHub** [comment]
The same as yours.Diving48.
My result is
mean_acc:0.4259
top1_acc: 0.5279
top5_acc: 0.8726.Do you have any other benckmarks' result?

**Comment by insist-arui** [comment]
My wechat is djr1102880600.Add Wechat


| |
邸继锐
|
|
***@***.***
|
签名由网易邮箱大师定制
On 5/29/2022 ***@***.***> wrote：

The same as yours.Diving48.
My result is
mean_acc:0.4259
top1_acc: 0.5279
top5_acc: 0.8726.Do you have any other benckmarks' result?

**Comment by insist-arui** [comment]
i dont change the config
