### ISSUE TITLE
Kinetics 400 dataset: duplicated files?

### ISSUE THREAD

**Issue by ryohachiuma** [kennymckormick/pyskl#42]
Hi, thank you for providing excellent code and also the dataset!
I'm trying to use the k400 dataset from the following instructions.
https://github.com/kennymckormick/pyskl/blob/main/tools/data/data_doc.md

However, when I try to extract the zip file(kpfiles.zip), the extractor warns that there are 2,652 pkl files that have the same name.
Is it ok to replace the files which have the same name? Is it expected behavior?  

Thank you in advance!

**Comment by kennymckormick** [comment]
Oh, maybe you have noticed that you can only extract these annotation files on a linux machine. Since Windows doesn't differentiate upper and lower case, there will be fewer extracted files.
