### ISSUE TITLE
how to obtain the 2s or 4s fusion test result?

### ISSUE THREAD

**Issue by smq20181217** [kennymckormick/pyskl#46]

**Comment by kennymckormick** [comment]
It's easy. You first need to train a model for each stream and test the model to get a pickle file (which contains the predicted scores for this stream). Then you can get the weighted average of the 2s (1:1) or 4s (2:2:1:1) scores, which are the fusion results.

**Comment by smq20181217** [comment]
Thanks for your answer !

**Comment by OskarIkaAdi** [comment]
sorry I'm confused, do you provide the code here
