### ISSUE TITLE
Regarding the 2D heat map generated from GT's .pkl file on the Finegym dataset, which part of the body is represented by the number of keypoints

### ISSUE THREAD

**Issue by HaleYan** [kennymckormick/pyskl#47]
Regarding the 17 keypoints in the Finegym dataset, I want to know, for example, which keypoint represents the left eye, just want to know the specific correspondence.

**Comment by kennymckormick** [comment]
Hi, HaleYan, 
    We follow the widely used  coco keypoint definition. That's the keypoint order (index from 0 to 16)

![image](https://user-images.githubusercontent.com/34324155/174464381-b783b5c4-6819-477a-95e0-0b5e8b972ec0.png)
