### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by taliegemen** [kennymckormick/pyskl#48]
in which guide should I follow to train my custom dataset with posec3d? Should I follow the one in mmaction2 or is there a different one for pyskl? Thanks.

**Comment by dongxiaolong** [comment]
I also want to know this. I am reading example code, I need to train this model on custom dataset.

**Comment by kennymckormick** [comment]
To train your custom dataset, there is only one additional step: you need to first generate the pickle file that contains the skeleton annotations. Then you can run the configs 
To generate the pickle file for your custom video dataset, you can follow the [diving48_example](https://github.com/kennymckormick/pyskl/blob/main/examples/extract_diving48_skeleton/diving48_example.ipynb). 
Currently, we perform no post processing to the estimated poses, you may add some post processing to meet your specific needs.

**Comment by Jinji97** [comment]
> 我应该遵循哪个指南来使用posec3d训练我的自定义数据集？我应该遵循 mmaction2 中的那个还是 pyskl 中的另一个？谢谢。
请问您现在知道自定义数据的格式么，可以分享下么，十分感谢

**Comment by kennymckormick** [comment]
> > 我应该遵循哪个指南来使用posec3d训练我的自定义数据集？我应该遵循 mmaction2 中的那个还是 pyskl 中的另一个？谢谢。
> > 请问您现在知道自定义数据的格式么，可以分享下么，十分感谢

Please follow the guideline in PYSKL.
Please refer to the diving48 example in PYSKL for training your custom datasets.
