### ISSUE TITLE
How to implement posec3D on my own computer

### ISSUE THREAD

**Issue by Sherryxingxing** [kennymckormick/pyskl#5]
Hello, I would like to ask you how to achieve PoseC3D in your own computer?
Is there anything else to be configured after the requirement is configured?
Which file do I need to run？

**Comment by kennymckormick** [comment]
Hi, Sherry, 
I have some difficulties to understand ur problem. 
To run posec3d, you just need to install this repo, download the annotations pickle files in https://github.com/kennymckormick/pyskl/blob/main/tools/data/data_list.md and follow the instruction for training & testing in the README of each algorithm.
