### ISSUE TITLE
About  the format of "viodes_list"  in the custom_2d_skeleton.py 

### ISSUE THREAD

**Issue by zw20yz** [kennymckormick/pyskl#50]
Hello, Ph.D. Duan. I want to konw the format of the "--videos_list" for the whole dataset. for example: UCF101, they have many folders with multiple labels, according to the comments is it necessary to put them all on one line? Could you give me a sample, please?

**Comment by kennymckormick** [comment]
Hi, zw20yz. 
The format should be: 
`````
/path/to/video_a.mp4 label_index
/path/to/video_b.mp4 label_index
`````
label_index is a number starts from 0.

**Comment by zw20yz** [comment]
Thank you, Ph.D.
