### ISSUE TITLE
为什么我stgcn++跑出来和stgcn一个效果，单GPU，哪里需要改吗？

### ISSUE THREAD

**Issue by llxyw** [kennymckormick/pyskl#51]

**Comment by kennymckormick** [comment]
idk, please add some more detailed descriptions.

**Comment by llxyw** [comment]
我使用bash tools/dist_train.sh configs/stgcn++/stgcn++_ntu60_xsub_3dkp/j.py 1 --validate --test-last --test-best命令训练，1080Ti，结果如下
![image](https://user-images.githubusercontent.com/66395575/176077578-713bf2ae-dcbc-4f20-b656-d2105714c030.png)
是必须使用8GPU才行吗

**Comment by kennymckormick** [comment]
You reduce #GPUs to 1, which makes the batch size reduced to 1/8 of the original. I recommend you reduce the learning rate proportionally.

**Comment by llxyw** [comment]
谢谢，我试了一下，效果很好

**Comment by kennymckormick** [comment]
Nice !
