### ISSUE TITLE
an error about extracting diving48_annos.pkl

### ISSUE THREAD

**Issue by Caicaizi-cdy** [kennymckormick/pyskl#53]
Dear kenny,
 First of all, thank you for your excellent work！Recently, I am trying to run your code of pyskl. However, I have met a problem about examples/extract_diving48_skeleton.

I would like to get diving48_annos.pkl through following your notebook diving48_example.ipynb. But when I run the code, there is a  error:

 raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/anaconda3/envs/cdpytorch/bin/python', '-u', 'tools/data/custom_2d_skeleton.py', '--local_rank=1', '--video-list', 'examples/extract_diving48_skeleton/diving48.list', '--out', 'examples/extract_diving48_skeleton/diving48_annos.pkl']' died with <Signals.SIGSEGV: 11>.

I have checked the github issue and searched on the Internet. Unfortunately, I haven't found relevant solutions. So I sent you an email, hoping to get your help！Thank you very much!

**Comment by Caicaizi-cdy** [comment]
![A%$_CYBPTP{3_AU}9AWSZ3X](https://user-images.githubusercontent.com/66052316/177277740-910d5e32-d935-40e6-8fc9-105e31658f5d.png)

**Comment by SLEEPYBQ** [comment]
Have you solved it by making environment again? I don't know which package has conflict with another package?
