### ISSUE TITLE
Versions of mmcv-full, mmdet, pytorch, cuda for running the repo

### ISSUE THREAD

**Issue by kiranganesh-rai** [kennymckormick/pyskl#54]
Hi, thanks for your awesome work! Is it possible for you to provide the versions of mmcv-full, mmdet, pytorch, cuda for successful running of the repo or point to a dockerfile ? Thank you!

**Comment by kiranganesh-rai** [comment]
![image](https://user-images.githubusercontent.com/107003903/177619151-41c054f3-2e33-43da-85ff-be539e76149c.png)

**Comment by kiranganesh-rai** [comment]
This was a mmcv build issue and I solved it by building mmcv from source instead of using the pre-built binary.

**Comment by wys2929** [comment]
Hello, is there any link or tutorial that I can refer to, I also encountered this problem, I don't know how to solve it, I look forward to your reply, thank you very much.

**Comment by kiranganesh-rai** [comment]
Hey @wys2929, it's a mmcv build issue. I solved it by running a `pip install mmcv-full`, instead of using a pre-built binary provided by mmcv.
