### ISSUE TITLE
How can i look at the plots losses?

### ISSUE THREAD

**Issue by watermellon2018** [kennymckormick/pyskl#55]
I want to watch changing train loss and validation loss, example wandb or just simple plots. How i can do that? This framework provides such an opportunity?
Thanks

**Comment by kennymckormick** [comment]
Basically, you need to modify this line: 
https://github.com/kennymckormick/pyskl/blob/51ffe9f338c3e911f743bd2c3aa5dcceec6a99a3/configs/stgcn%2B%2B/stgcn%2B%2B_ntu60_xsub_3dkp/j.py#L59
You can add some other logger hooks to do that, like TensorboardLoggerHook or WandbLoggerHook (and then visualize the curve in tensorboard or wandb), this feature is supported in mmcv. Check this for the list of all supported logger hooks: 
https://github.com/open-mmlab/mmcv/blob/94c071b31088fd29640377ef46ac123d28cb9bfe/mmcv/runner/hooks/logger/__init__.py
