### ISSUE TITLE
another error about extracting the skeleton of diving48

### ISSUE THREAD

**Issue by Caicaizi-cdy** [kennymckormick/pyskl#56]
Hi！Kenny！ Thank you for sharing such excellent work！I have met another error when extracting the skeleton of diving48. I felt very confused.

I can run demo successfully. 

However, when I run custom_2d_skeleton.py, there is an error about init_detector and init_pose_model

If I use the original code
![28)}MGM ~V1%D7I9O38HL$D](https://user-images.githubusercontent.com/66052316/177784168-5075f074-0271-4f55-a7d5-45d47336a841.png)

If I modify the default_det_config and default_det_ckpt according demo_skeleton.py
![2NQTO43_B7`261ZRRU}D7)D](https://user-images.githubusercontent.com/66052316/177784248-633dde15-ba25-4282-b86e-d51b16c73658.jpg)

I really don't know how to solve the problem, if anyone meet the same problem like me , please help me, thank you.

**Comment by kennymckormick** [comment]
Hi, please install the mmdet & mmpose from source, with the development mode, like `pip install -e .`

**Comment by Caicaizi-cdy** [comment]
@kennymckormick Thanks a lot, I will have a try.
