### ISSUE TITLE
some questions about the pretrained 2d model in resnet3d

### ISSUE THREAD

**Issue by Caicaizi-cdy** [kennymckormick/pyskl#57]
Hi, Kenny. Thank you for sharing such excellent work.

Recently, I am learning the ResNet3dSlowOnly in pyskl .

I feel confused about the parameter pretrained2d(bool): Whether to load pretrained 2D model. Default: True, In class ResNet3d of models/cnns/resnet3d.py. 

1. In the original code, self.pretrained2d = True, I think it means you use the pretrained 2D model. However I can't find the loaded pretrained 2D model and I don't know where the pretrained 
model is loaded (torchvision? or other places? I can't find the relative code to appoint it).

2. If I set pretrained2d = False, Can I still train normally? Will the final result be much worse than when loading the pretrained 2D model?

Sincerely hope to get your reply!

**Comment by kennymckormick** [comment]
Hi, actually, 'pretrained2d=True' only means **if** pretrained weight is used, it is the weight of a 2D-CNN. However, pretrained is None by default, which means no pretrained weight is used in all PoseC3D experiments.

**Comment by Caicaizi-cdy** [comment]
@kennymckormick Thank you for your answer. I understand!
