### ISSUE TITLE
provide a script for stgcn++ score fusion?

### ISSUE THREAD

**Issue by YF729** [kennymckormick/pyskl#59]

**Comment by kennymckormick** [comment]
I can provide you a simple sample:
Lets say you want to report the joint + bone fusion accuracy (1:1) on nturgb+d xsub split, the prediction files are j.pkl and b.pkl, while the annotation file is ntu60_3danno.pkl

```
from mmcv import load, dump
from pyskl.smp import *
joint, bone = load('j.pkl'), load('b.pkl')
label = load_label('ntu60_3danno.pkl', 'xsub_val')
fused = comb([joint, bone], [1, 1])
print('Top-1', top1(fuse, label))
```
