### ISSUE TITLE
 During visualization, prompt the following error

### ISSUE THREAD

**Issue by honggang0524** [kennymckormick/pyskl#6]
I have built the environment according to the documents, dist_train.sh can work.

Traceback (most recent call last):
  File "vision_skeleton.py", line 13, in <module>
    anno = annotations[index]
KeyError: 0

**Comment by kennymckormick** [comment]
Please refer to [vis_skeleton.ipynb](https://github.com/kennymckormick/pyskl/blob/main/demo/vis_skeleton.ipynb) on how to use the provided visualization APIs.
