### ISSUE TITLE
How to get and store the keypoint heatmap volume as pkl file directly？

### ISSUE THREAD

**Issue by aleeyang** [kennymckormick/pyskl#60]
**Thank you for your great work on PoseC3D!**
I am trying to use the heatmap volume from PoseC3D as my model input.
I have already follow 'custom_skeleon_2D.py' to generate the **pkl file** in my dataset.
I need to **generate the heatmap volume** though the pkl file and store the heatmap volume as pkl file as my model input(How to generate it?Is there a way to set the heatmap size(width,height,channle)?)
Can you me some tips or suggestions?
_**Thank you very much!**_

**Comment by kennymckormick** [comment]
Hi, Aleeyang,  
    To generate the heatmap volume through the pickle file, you just need to follow the data_pipeline, which is included in each config of PoseC3D. You can also refer to the heatmap volume visualization demo: https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb for guides on practice.

**Comment by aleeyang** [comment]
Thank you very much!
I have already got the heatmap volume data
But in my dataset, there is only one person in videos.However, the result show there are tow person.
Is there way to set the  person number （to 1）of detection  model? 

It like this which set the category to person
https://github.com/kennymckormick/pyskl/blob/51ffe9f338c3e911f743bd2c3aa5dcceec6a99a3/tools/data/custom_2d_skeleton.py#L129
Thank you

**Comment by kennymckormick** [comment]
Hi, Alee. Basically you can not set the person number for a detection model. But what you can do is to do some post-processing yourself to keep only one person per frame. It could be some heuristics like keeping the person with largest box confidence score, the largest box area, or the largest overall keypoint confidence score.

**Comment by aleeyang** [comment]
Thank you very much!
