### ISSUE TITLE
Invalid index to scalar variable on ntu_pose_extraction.py

### ISSUE THREAD

**Issue by taliegemen** [kennymckormick/pyskl#62]
Hello I am obtaining the following error when I am using the ntu_pose_extraction.py tool for my custom dataset. 
Why this error happens and how can i fix it? Thanks!
`File "ntu_pose_extraction.py", line 346, in <module>
    anno = ntu_pose_extraction(args.video, args.skip_postproc)
  File "ntu_pose_extraction.py", line 315, in ntu_pose_extraction
    pose_results = pose_inference(args, frame_paths, det_results)
  File "ntu_pose_extraction.py", line 302, in pose_inference
    d = [dict(bbox=x) for x in list(d) if x[-1] > 0.5]
  File "ntu_pose_extraction.py", line 302, in <listcomp>
    d = [dict(bbox=x) for x in list(d) if x[-1] > 0.5]
IndexError: invalid index to scalar variable.`

**Comment by kennymckormick** [comment]
Hi, Taliegemen,
Please do not use ntu_pose_extraction.py to process a custom dataset. For custom dataset processing, please refer to this example: https://github.com/kennymckormick/pyskl/blob/main/examples/extract_diving48_skeleton/diving48_example.ipynb

**Comment by taliegemen** [comment]
But I have the same action labels and I used the same naming scheme for my data. do I still need to follow this example? because my data resembles a lot of ntu.
Thanks!

**Comment by kennymckormick** [comment]
The problem is, `ntu_pose_extraction.py` relies on the assumption that there exist one or two persons in each frame. I guess you meet the problem cuz there is no person found in some of your video frames. You need to modify the codes to support that case if you want to use the script.

**Comment by taliegemen** [comment]
I see, so there has to be a one or two person each frame and the frame should include the persons from feet to head. In some pictures of my data feet is out of the frame, i guess this error happens because of that. Thanks!
