### ISSUE TITLE
When will the model of RGBPoseC3D be released?

### ISSUE THREAD

**Issue by troublecmd** [kennymckormick/pyskl#63]
Thinks for your great work, and I want to know how soon will the fusion model be relased?
thanks a lot.

**Comment by insist-arui** [comment]
i am studing how to fuse the rgb and pose，can we have a talk？

**Comment by kennymckormick** [comment]
Finally, I have implemented RGBPoseConv3D in PYSKL 🤣 . The implementation is in PR https://github.com/kennymckormick/pyskl/pull/116 and has been merged to the main branch.
