### ISSUE TITLE
test posec3d on Kinetics400

### ISSUE THREAD

**Issue by MikuuGithub** [kennymckormick/pyskl#64]
I put the kpfiles folder and the k400_hrnet.pkl file in the same directory. 
I used slowonly_r50_346_k400/joint.py as config file and set ‘memcached’ = False.
When i run tools/test.py, an error occured.
Please help me!!!
![image](https://user-images.githubusercontent.com/24295745/179779941-61198bd1-add8-4735-9946-b64b8508e437.png)

**Comment by kennymckormick** [comment]
You need to make sure that the memcached service successfully started & you can read or write objects from it. BTW, I'm not sure if memcached supports windows machine (guess not).

**Comment by MikuuGithub** [comment]
> You need to make sure that the memcached service successfully started & you can read or write objects from it. BTW, I'm not sure if memcached supports windows machine (guess not).

Yes, I had solved the problem. By the way, memcached also supports windows machine. It should be noted that if you use windows, you need to change backend='nccl' to backend='gloo'.
