### ISSUE TITLE
generating joint heat maps

### ISSUE THREAD

**Issue by Sharath-chandra45** [kennymckormick/pyskl#65]
In the paper there is formula for generating joint heatmap J for joints by generating k heatmaps

Jkij = (e**−((i−xk)**2+(j−yk)**2)/2∗σ2) ∗ ck,

can you please tell me what are the default values of i,j and variance values

Thanks in advance

**Comment by kennymckormick** [comment]
Hi, Sharath, 
i, j are indices on the 2d heatmap and do not have default values. 
sigma is 0.6 in our experiments (the typical size of heatmap is 48 to 64).

**Comment by Sharath-chandra45** [comment]
Thanks for the reply sir
