### ISSUE TITLE
The question about mean top 1 on finegym

### ISSUE THREAD

**Issue by insist-arui** [kennymckormick/pyskl#66]
The paper report the mean top 1 on gym. the evaluation dict in config for gym is['top_k_accuracy  mean class accuracy '] ,when i test with the default config, the result is the mean top 1 accuracy?

**Comment by kennymckormick** [comment]
Hi, Rui,
You can see three numbers when you run experiments with the default config file, which is top-1, top-5, and mean top-1. Just pick the right number.

**Comment by insist-arui** [comment]
> Hi, Rui, You can see three numbers when you run experiments with the default config file, which is top-1, top-5, and mean top-1. Just pick the right number.

thank for your answer，the mean_class_accuracy is the mean top 1  on gym in the paper,am i right?

**Comment by kennymckormick** [comment]
Yes, that's right.
