### ISSUE TITLE
How to change cuda device

### ISSUE THREAD

**Issue by a-github-learner** [kennymckormick/pyskl#68]
I wanted to change my device form 'cuda:0' to 'cuda:1',then I met the problem below. It shows that I didn't totally run my code on the new device.  Where should I modify in this program to run my code on the new device? thanks!

![1658925920981](https://user-images.githubusercontent.com/78460513/181249943-b6514a4f-5700-4ae6-a361-87787b237eb0.jpg)

**Comment by kennymckormick** [comment]
To run training on `cuda:1`, you can use CUDA_VISIBLE_DEVICES=1 bash tools/dist_train.sh blahblah ...

**Comment by a-github-learner** [comment]
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kennymckormick/pyskl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 凌晨3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kennymckormick/pyskl] How to change cuda device (Issue #68)





 
To run training on cuda:1, you can use CUDA_VISIBLE_DEVICES=1 bash tools/dist_train.sh blahblah ...

**Comment by a-github-learner** [comment]
Thanks!
