### ISSUE TITLE
Generating Pseudo Headmap Volumes

### ISSUE THREAD

**Issue by Matus-Tanonwong** [kennymckormick/pyskl#7]
Hello there!!
Thank you very much for such great work!
Could you please let me know where I can find "GenPseudoHeadmaps.ipynb"?

Thank you very much in advance

**Comment by kennymckormick** [comment]
Please try [visualize_heatmap_volume.ipynb](https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb), basically they are the same.

**Comment by Matus-Tanonwong** [comment]
Thank you very much for your kind response.
I have already tried ''visualize_heatmap_volume.ipynb'' as you suggested but confronted another problem.
The heatmap visualizations for both keypoints and limbs are rotated (after vid.ipython_display( )).
I have been trying to fix the codes by myself but still cannot find the way.
Could you please give me some guidance?

Thank you very much for your consideration

**Comment by kennymckormick** [comment]
> Thank you very much for your kind guidance. I apologize for my late response. I have been looking for where x and y might have been reversed, but still haven't found them. Can you run the codes and correctly get the heatmap volumes in upright positions?

Sorry that I found there exists a bug in the old ''visualize_heatmap_volume.ipynb'' and have fixed it, please try the latest version.

**Comment by Matus-Tanonwong** [comment]
Thank you very much for your support and guidance.
Yes, its latest version works fine.
