### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by gsrujana** [kennymckormick/pyskl#70]
Hello,

Thanks for the wonderful work. Can you please provide an overview on inference time of this model? Does it work in realtime? Can we use it on live camera feed? Would it need a gpu or can run on cpu?

Thanks

**Comment by lbycan** [comment]
Can I train the model on cpu?

**Comment by kennymckormick** [comment]
> Can I train the model on cpu?

I think No. I have tried to train those algorithms with CPU (with multiprocessing), but the training speed is just so slow (around 20 times slower than GPU training). Thus I didn't add this in the PYSKL codebase.

**Comment by kennymckormick** [comment]
Hi, [gsrujana](https://github.com/gsrujana), you can use this script: https://github.com/kennymckormick/pyskl/blob/main/examples/inference_speed.ipynb to estimate the inference speed of each model, note that it's just a rough estimation. 

Some estimation results obtained by myself:
| Device / FPS | AAGCN | CTRGCN | DGSTGCN | MSG3D | STGCN | STGCN++ | PoseC3D | Notes |
|--|--|--|--|--|--|--|--|--|
| 2080Ti (Linux) | 274 | 353 | 409 | 111 | 518 | 476 | 41 | Iters 100, Warmup 100 |
| 3060 (Windows) | 135 | 148 | 181 | 50 | 206 | 186 | 38 | Iters 100, Warmup 100 |
| CPU (11800H Windows) | 7.5 | 7.2 | 8.1 | 4.3 | 13.8 | 8.9 | 2.9 | Iters 10, Warmup 10 |

**Comment by Fanthers** [comment]
> > Can I train the model on cpu?
> 
> I think No. I have tried to train those algorithms with CPU (with multiprocessing), but the training speed is just so slow (around 20 times slower than GPU training). Thus I didn't add this in the PYSKL codebase.

Is it okay if I test on the CPU
