### ISSUE TITLE
No model named pyskl while testio

### ISSUE THREAD

**Issue by a-github-learner** [kennymckormick/pyskl#71]
I always got error named "No module named 'pyskl'" if I ran bush dist_test.sh. After checking correction of my config and checkpoint root , I have no idea for the error.  

![1659246699507](https://user-images.githubusercontent.com/78460513/182012273-9d9c1563-1013-474c-b768-25545232c36c.jpg)

![image](https://user-images.githubusercontent.com/78460513/182012285-2b032ede-beaf-4083-a7d8-f39d7a15b276.png)

**Comment by kennymckormick** [comment]
run `pip install -e .` under pyskl folder, installation is required to use the software

**Comment by a-github-learner** [comment]
It does work. Thanks!
