### ISSUE TITLE
Segmentation fault (core dumped) with some pretrained models (but not all) in creating my own skeleton data

### ISSUE THREAD

**Issue by suijua** [kennymckormick/pyskl#72]
Hello,

I have a strange issue when loading some pretrained models. On loading, some models abort and give an "Segmentation fault (core dumped)" message, like below:
![image](https://user-images.githubusercontent.com/98210579/182022090-92c7faee-be3e-40a1-bb98-a675d6bb000b.png)

**Comment by kennymckormick** [comment]
Do not directly use this python script, follow the usage in the ipython notebook and use dist_run.sh to launch the job.

**Comment by suijua** [comment]
> Do not directly use this python script, follow the usage in the ipython notebook and use dist_run.sh to launch the job.

Thamks for your reply!I I ran the above mentioned link, but it's something wrong just as this:
![image](https://user-images.githubusercontent.com/98210579/182083697-2565bf8e-86db-45b0-a5dc-a3bb527dfa57.png)

**Comment by kennymckormick** [comment]
Hi, I'm sorry, I cannot figure out what might be the problem. I haven't met that problem on every linux GPU server I used.

**Comment by suijua** [comment]
> Hi, I'm sorry, I cannot figure out what might be the problem. I haven't met that problem on every linux GPU server I us

**Comment by suijua** [comment]
> Hi, I'm sorry, I cannot figure out what might be the problem. I haven't met that problem on every linux GPU server I used.

Thank you for your reply! that is all right

**Comment by azelee** [comment]
![image](https://user-images.githubusercontent.com/73898764/223071640-2bbf5d04-90da-44e4-bdf5-56f8a244f5c9.png)
I have tried to change the parameter device of det_model and pose_model, and of course import torch is required! It works in term of my code and env

**Comment by AgileChen3** [comment]
> ![image](https://user-images.githubusercontent.com/73898764/223072374-b1372d4b-f3af-475a-9aa8-8720651691d6.png)
> 
> I have tried to change the parameter device of det_model and pose_model, and of course import torch is required! It works in term of my code and env

I have the same problem, Can you share your code with me， thank you

**Comment by azelee** [comment]
> > ![image](https://user-images.githubusercontent.com/73898764/223072374-b1372d4b-f3af-475a-9aa8-8720651691d6.png)
> > I have tried to change the parameter device of det_model and pose_model, and of course import torch is required! It works in term of my code and env
> 
> I have the same problem, Can you share your code with me， thank you

I just changed the det_model and pose_model as my notes above and insert import torch as well, It worked in my server!

**Comment by samouha** [comment]
Hi, 
@yuchen-ji  have you, please, solved this issue?
I have the same segmentation fault problem! And the proposed solution by @azelee doesn't work unfortunately :/

**Comment by kennymckormick** [comment]
Recently I also met this problem. I guess the potential reason be a new version of gcc is used to compile the open-mmlab codebases, which lead to some errors. Now I have fixed it by using a very specific conda environment for this project. Please following the [new installation guide](https://github.com/kennymckormick/pyskl/blob/051a094f9de6cbe9ddeb1f3a8f2754629691ca42/README.md?plain=1#L46) to reinstall pyskl and see if the problem has been fixed now. 
Sorry for the late fix.

**Comment by kennymckormick** [comment]
Feel free to re-open the issue if the problem still exists when you install following the latest installation guide.

**Comment by suijua** [comment]
> Feel free to re-open the issue if the problem still exists when you install following the latest installation guide.

ok, thanks for your work!

**Comment by JiaweiMorris** [comment]
> Recently I also met this problem. I guess the potential reason be a new version of gcc is used to compile the open-mmlab codebases, which lead to some errors. Now I have fixed it by using a very specific conda environment for this project. Please following the [new installation guide](https://github.com/kennymckormick/pyskl/blob/051a094f9de6cbe9ddeb1f3a8f2754629691ca42/README.md?plain=1#L46) to reinstall pyskl and see if the problem has been fixed now. Sorry for the late fix.

hi, I met the same problem again, and I followed the new installation guide or @azelee's solution but they didn't work.

**Comment by seekFire** [comment]
@JiaweiMorris I also met recently

**Comment by SLEEPYBQ** [comment]
I encountered the same question of **Segmentation fault (core dumped)**. Specifically, I solved this problem by changing my Torch version to **1.12.1**.

```bash
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://mirror.sjtu.edu.cn/pytorch-wheels/cu113
```

Subsequently, I found that the mmcv-full version has conflicts with the Torch version, so I changed the mmcv-full version to 1.6.2. After that, the existing mmdet and mmpose versions were also changed:

+ mmcv-full: 1.6.2
+ mmdet: 2.24.0
+ mmpose: 0.28.1

If you change these packages, you'll find your code can't run directly because of the version assert code:

```bash
(pyskl) admin1@ubuntu:~/jbhi_work/pyskl_2$ python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 16, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "/home/admin1/jbhi_work/pyskl/ENTER/envs/pyskl/lib/python3.7/site-packages/mmdet/__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.6.2 is used but incompatible. Please install mmcv>=1.3.17, <=1.6.0.
```

But you can comment out the following code in /home/admin1/jbhi_work/pyskl/ENTER/envs/pyskl/lib/python3.7/site-packages/mmdet/__init__.py:

```python
assert (mmcv_version >= digit_version(mmcv_minimum_version)
        and mmcv_version <= digit_version(mmcv_maximum_version)), \
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
    f'Please install mmcv>={mmcv_minimum_version}, <={mmcv_maximum_version}.'
```

After completing these steps, the **Segmentation fault (core dumped)** issue was resolved.
