### ISSUE TITLE
Preprocessed RGB images

### ISSUE THREAD

**Issue by chenyangjamie** [kennymckormick/pyskl#74]
Thanks for sharing this great work!
I wonder is that possible to share the preprocessed RGB data (or just scripts) from NTU and NTU-120 datasets? Thanks.

**Comment by Hao-Quan** [comment]
I also need it, hoping could be provided. (Heatmap of NTU 60 and 120 datasets)

**Comment by kennymckormick** [comment]
Hi, I can not share the preprocessed RGB frames due to the copyright issues. You need to download the videos from the official website. Once you downloaded them, you can follow the guides in https://github.com/kennymckormick/pyskl/tree/main/configs/rgbpose_conv3d and use them in RGBPoseConv3D.
