### ISSUE TITLE
PoseConv3D validation/test pipeline

### ISSUE THREAD

**Issue by ahmed-nady** [kennymckormick/pyskl#77]
Thanks for your great work. I have question regarding spatial size of pseudo heatmaps, in training pipeline, the size 58 X58 but in validation and test pipeline, the size of heatmap is 64X64. why you do validation and test with 64x64 instead of the 58x58?

**Comment by kennymckormick** [comment]
Hi, ahmed-nady, 
That's a common practice in general image / video recognition. For example, many works using 224 x 224 as the training resolution, and 256 x 256 as the testing resolution. 
BTW, our training resolution is 56 x 56 :lol
