### ISSUE TITLE
CTR GCN architecture explaination??

### ISSUE THREAD

**Issue by viet-hoang-99** [kennymckormick/pyskl#83]
![image](https://user-images.githubusercontent.com/87934114/189060582-4557ef91-ab07-4b26-b71c-9848c631ac9e.png)
i think it should be Sequential not Module List. In the original paper Channel-wise Topology Refinement Graph Convolution for Skeleton-Based Action Recognition, they said they had 10 blocks of CTR GC and the input features of the each block is the output features of the previous one and at their github https://github.com/Uason-Chen/CTR-GCN have the same architecture.
May I miss something?

**Comment by kennymckormick** [comment]
Emmm, please check the forward function. Actually, we are just doing what u described.
