### ISSUE TITLE
Script to create dataset?

### ISSUE THREAD

**Issue by viet-hoang-99** [kennymckormick/pyskl#84]
Do you have any script for generate skeleton ground truth heatmap for the input of PoseC3D model? I really don't know about the information of model input like heatmap type, heatmap size,...
Now I have my own dataset by generating short video into coordinate by pose estimator. With each video i have a label file which stores keypoints coordinate of each frame. And I want to convert keypoints coordinate into 3d heatmap, is there any instruction?
Thanks!

**Comment by hoangdung2000** [comment]
I have same question for that . Can anyone help ???

**Comment by lbycan** [comment]
The datasets of Posec3d and gcn are same. You can print out the keys of the pkl dataset. You can use the script "tools/data/custom_2d_skeleton.py" to generate your own  keypoint dataset. While loading data, I think it will use "pyskl/datasets/pipelines/heatmap_related.py" to generate the heatamp from keypoints.

**Comment by kennymckormick** [comment]
For visualization, you can use https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb, it 
converts keypoint coordinates to 3D heatmap volumes and visualize them. If you want to do it in training, that is implemented as data pipeline components, please refer to one of the released PoseC3D configs for more details.

**Comment by manhcntt21** [comment]
@viet-hoang-99 bạn ơi, mình muốn trao đổi thêm với bạn về đề tài này được không?
