### ISSUE TITLE
GenPseudoHeatmaps.ipynb

### ISSUE THREAD

**Issue by Lee-ray-a** [kennymckormick/pyskl#86]
Where I can find ``GenPseudoHeatmaps.ipynb`` that is mentioned in the **Revisiting Skeleton-based Action Recognition** essay?

**Comment by kennymckormick** [comment]
That is https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb in this codebase.

**Comment by Lee-ray-a** [comment]
Thanks, great work by the way.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kennymckormick/pyskl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 凌晨1:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kennymckormick/pyskl] GenPseudoHeatmaps.ipynb (Issue #86)





 
That is https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb in this codebase.
