### ISSUE TITLE
error when run python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4

### ISSUE THREAD

**Issue by manhcntt21** [kennymckormick/pyskl#87]
Thanks for sharing the implementation. When running the demo, the following error message. Please advice.

`
(pyskl) PS D:\CODE\master\pyskl> python demo/demo_skeleton.py demo/ntu_sample.avi demo/demo.mp4
load checkpoint from local path: .cache\joint_f6bed715.pth
load checkpoint from http path: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
Performing Human Detection for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 72/72, 4.9 task/s, elapsed: 15s, ETA:     0sPerforming Human Pose Estimation for each frame
[                                                  ] 0/72, elapsed: 0s, ETA:Traceback (most recent call last):
  File "D:\CODE\master\pyskl\demo\demo_skeleton.py", line 311, in <module>
    main()
  File "D:\CODE\master\pyskl\demo\demo_skeleton.py", line 255, in main
    pose_results = pose_inference(args, frame_paths, det_results)
  File "D:\CODE\master\pyskl\demo\demo_skeleton.py", line 181, in pose_inference
    pose = inference_top_down_pose_model(model, f, d, format='xyxy')[0]
TypeError: 'NoneType' object is not subscriptable
`
Computer:
GTX 1660TI
Windows 10
Chip AMD Ryzen 3700

Installation:
python3.10 or python3.9 (I tried both)
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
pip install -r requirements.txt
pip install -e .
pip install openmim
mim install mmcv-full
mim install mmdet

Please, help me. Indeed, can you share exactly version packages you install. Thanks

**Comment by kennymckormick** [comment]
Hi, seems that the problem is the function call `inference_top_down_pose_model(model, f, d, format='xyxy')` returned `None`, which is not the expected behavior. I suggest you delve deep into this problem and try to fix.

**Comment by manhcntt21** [comment]
thanks

**Comment by lxlcry** [comment]
> thanks

Hello, how did you solve it, I also encountered this problem
