### ISSUE TITLE
demo_stgcn++

### ISSUE THREAD

**Issue by jeongeun12** [kennymckormick/pyskl#9]
i followed your suggestion, 
@kennymckormick
Collaborator
[kennymckormick](https://github.com/kennymckormick) commented [14 days ago](https://github.com/open-mmlab/mmaction2/issues/1575#issuecomment-1095973718)
Hi, jeongeun12,
Currently PoseC3D does not support training with 3d joints directly. To use PoseC3D, you need to first project 3d keypoints to 2d keypoints (for example, find a project view that reserve the majority of inter-keypoint variance).
If you want to directly use 3d joints for training, I recommend you to move to [PYSKL](https://github.com/kennymckormick/pyskl), where we released an original SOTA gcn model named ST-GCN++

i finally trained st_gcn++ with 3d kp datasets,and i want to demo it. 
is it ok that i use **inference_recognizer model** in demo_posec3d code ??

**Comment by jeongeun12** [comment]
is inference_ recognizer model only able to be used in 2d skeleton ?
how can i demo or test action classification model with 3d skeleton??

**Comment by kennymckormick** [comment]
> 

Hey, [jeongeun12](https://github.com/jeongeun12), 
for that case you can replace `pose_inference` part in `demo_skeleton` with your own pose_inference approach, and pack the skeleton sequences into the right format.
