### ISSUE TITLE
About how the hmdb51 and ucf101 dataset is divided into training part and test part

### ISSUE THREAD

**Issue by HaleYan** [kennymckormick/pyskl#91]
Thanks for your great work !
In the experiment, you have done the experiment of hmdb51 and ucf101 dataset and presented the results in the paper, but in [mmaction2/tools/data/skeleton/README](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton), unlike other datasets will be divided into train and val parts. When I studied the provided hundb.pkl and ucf101.pkl I found that although there are points '`spilt`' and '`annotations`', in '`spilt`', there are only characters` train1, train2, train3, test1, test2, test3`. So I don't know how the two datasets are divided into training part and test part.

**Comment by kennymckormick** [comment]
Hi, HaleYan, for UCF101 and HMDB51, we use the official split released with the original dataset. Please refer to the original paper of these datasets to get the split information.
