### ISSUE TITLE
One class training for custom dataset

### ISSUE THREAD

**Issue by nadhiranoor** [kennymckormick/pyskl#93]
is it possible to train on one class dataset? I tried to train it however the accuracy is 100% since the first epoch.
the dataset has 250 training videos, and 73 testing videos all one label which is falling down.
![image](https://user-images.githubusercontent.com/28914051/196430781-a110daac-737d-4dcb-b827-56d0a701aac8.png)

**Comment by kennymckormick** [comment]
Hi, nadhiranoor,
    If you want to train models for a single action category, at least you will need some negative samples (videos not performing "falling down" in your case). Then you can train a two-way classifier to recognize falling down or not. Also, in that case you should care about precision & recall, not the classification accuracy.
